backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "cars"
    label: "Cars"
    folder: "data/cars"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Body", name: "body", widget: "string" }
      - { label: "Fuel", name: "fuel", widget: "string" }
      - { label: "KM", name: "km", widget: "string" }
      - { label: "Transmission", name: "trans", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }